version: "3.4"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
     - ./dev.env
    command: [ "npm", "run", "start-debug" ]
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /app/node_modules
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"