version: "3.4"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
     - ./dev.env
    command: [ "npm", "run", "start-debug" ]
    volumes:
      - .:/app
      - /app/node_modules